name: test1

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: setup node.js
      uses: actions/setup-node@v4
      with: 
        node-version: '24'   

    - name: install dependencies
      run: npm install --legacy-peer-deps

    - name: Enable KVM
      run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0660", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        target: default
        arch: x86_64
        profile: pixel_7_pro
        script: |
          adb install apps/wikipedia.apk
          npm run wdio
      continue-on-error: true



